home work oop
diasel2000/OOP_HW pull request #1
Opened 2019-04-07 12:24 UTC by diasel2000

2019-04-10 15:35 UTC, grishasht commented on src/main/java/HW_OOP/candies/BaseCandy.java
> +
Одобряю. Затверджено. Прийнято

2019-04-10 15:36 UTC, diasel2000 commented on src/main/java/HW_OOP/candies/BaseCandy.java
> +
Ураааааа!!!!

2019-04-25 14:30 UTC, valeriiafatova requested changes

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/candies/BaseCandy.java
> +
Package name convention missed

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/candies/BaseCandy.java
> +        if(weight<=0){
REMOVE LOGIC FROM MODEL

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/candies/BaseCandy.java
> +    public enum  candyType {
Remove commented code

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/candies/Candy.java
> +//    void select();
Remove commented code

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/candies/CandyCaramel.java
> +
remove empty line

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +    public ArrayList<Candy> firstColection(){
Declare Interface List instead of implementation

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +        list.add (chocolatBat2);
Formatting should be done

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +        ArrayList<Candy> list = giftBox.firstColection ();
List

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +
Line

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +                System.out.println(i + ".   " + vault.getName() + "    " + vault.getPrice () + "       " + vault.getWeight()+"       "+vault.getShugar ());
Replace with printf

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +    public double getFullGiftWeight(ArrayList<Candy> list, double sumWeight) {
Declare list

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +        Scanner sc = new Scanner ( System.in );
Do not create new Scanner object when you need use r input. Move to separate class functionality

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftBox.java
> +        StringBuilder item = findCandyByPrice ( a,b,list);
Do not make StringBuilder as return type if in the end you just need String. In method just call stringBuilder.toString()

2019-04-25 14:30 UTC, valeriiafatova commented on src/main/java/HW_OOP/editor/GiftFactory.java
> +    public void getFullColection(ArrayList<Candy> list);
declare List

2019-04-25 14:30 UTC, valeriiafatova commented on src/test/java/HW_OOP/AppTest.java
> +public class AppTest
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2019-05-08 11:01 UTC, merged